### ISSUE TITLE
Le script gatling cherche une attribut absent du swagger

### ISSUE THREAD

**Issue by dpiraud** [ltoinel/IoT-Development-Challenge#20]
Bonsoir,
Pendant mes tentatives de ce soir et sauf erreur de ma part, le script gatling semble chercher un attribut de la synthèse qui n'est pas défini dans le swagger (SynthesisSensor+index du capteur), la stack:

java.lang.UnsupportedOperationException: Can't call get on Failure(No attribute named 'SynthesisSensor5' is defined)
        at io.gatling.commons.validation.Failure.get(Validation.scala:50)
        at io.gatling.commons.validation.Failure.get(Validation.scala:42)
        at InjectionsAndVerifications$ScenarioBuilder$$anonfun$SendMsgsAndCHeckSynthesis$2.apply(script.scala:298)
        at InjectionsAndVerifications$ScenarioBuilder$$anonfun$SendMsgsAndCHeckSynthesis$2.apply(script.scala:296)
        at io.gatling.core.action.SessionHook.execute(SessionHook.scala:38)
        at io.gatling.core.action.Action$class.$bang(Action.scala:35)
        at io.gatling.core.action.SessionHook.io$gatling$core$action$ChainableAction$$super$$bang(SessionHook.scala:30)
        at io.gatling.core.action.ChainableAction$class.$bang(Action.scala:60)
        at io.gatling.core.action.builder.SessionHookBuilder$$anon$1.io$gatling$core$action$ExitableAction$$super$$bang(SessionHookBuilder.scala:35)
        at io.gatling.core.action.ExitableAction$class.io$gatling$core$action$ExitableAction$class$$$anonfun$3(BlockExit.scala:140)
        at io.gatling.core.action.ExitableAction$class.io$gatling$core$action$ExitableAction$class$$$anonfun$3$adapted(BlockExit.scala:140)
        at io.gatling.core.action.ExitableAction$.exitOrElse(BlockExit.scala:125)
        at io.gatling.core.action.ExitableAction$class.$bang(BlockExit.scala:140)
        at io.gatling.core.action.builder.SessionHookBuilder$$anon$1.$bang(SessionHookBuilder.scala:35)
        at io.gatling.http.ahc.ResponseProcessor.executeNext(ResponseProcessor.scala:144)
        at io.gatling.http.ahc.ResponseProcessor.logAndExecuteNext(ResponseProcessor.scala:169)
        at io.gatling.http.ahc.ResponseProcessor.checkAndProceed$1(ResponseProcessor.scala:291)
        at io.gatling.http.ahc.ResponseProcessor.processResponse(ResponseProcessor.scala:321)
        at io.gatling.http.ahc.ResponseProcessor.onCompleted(ResponseProcessor.scala:61)
        at io.gatling.http.ahc.AsyncHandler.onCompleted(AsyncHandler.scala:127)
        at io.gatling.http.ahc.AsyncHandler.onCompleted(AsyncHandler.scala:46)
        at org.asynchttpclient.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:188)
        at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:223)
        at org.asynchttpclient.netty.handler.HttpHandler.finishUpdate(HttpHandler.java:58)
        at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:159)
        at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:189)
        at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:82)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Unknown Source)

**Comment by glandais** [comment]
Deux problèmes :
- il essaye d'intérroger http://127.0.0.1/ (baseUrl/url?)
- startTimePackage(sensorIndex) est à 0

**Comment by IsBena** [comment]
le problème n'est pas dans le swagger, pour tester ton URL tu doit indiquer ou tu as mis ton serveur pour pouvoir envoyer tes requêtes (post et get), ces fonction qui construisent les nom des requêtes n'ont aucun rapport avec le swagger ...je vérifierai demain et je reviens vers toi...

**Comment by dpiraud** [comment]
@IsBena Je pointe bien sur mon serveur, je vois les requêtes passer. Je check aussi demain le json que je génère pour les réponses à ".../messages/synthesis?..."

**Comment by IsBena** [comment]
synthesis envoi un json array ....qui contient 10 synthese (sur le swagger il y a les petits [] qui indique cela)

**Comment by dpiraud** [comment]
Je ferme ma demande: Il manquait une "," avant mon dernier objet dans ma réponse.
Petit site pour vérifier les json pour les autres participants: http://jsonlint.com/
Merci et Dsl ;)
